## 데이터선택

### Numpy 실습

In [5]:
import numpy as np

In [6]:
a = [1, 3.14, True, 'hello']
b = np.array(a)

In [7]:
# python 리스트 원소 데이터 타입 확인
print(a)
for e in a:
    print('Data type of {} : {}'.format(e, type(e)))

[1, 3.14, True, 'hello']
Data type of 1 : <class 'int'>
Data type of 3.14 : <class 'float'>
Data type of True : <class 'bool'>
Data type of hello : <class 'str'>


In [8]:
# Numpy 배열 원소 확인
print(b)
for e in b:
    print('Data type of {} : {}'.format(e, type(e)))

['1' '3.14' 'True' 'hello']
Data type of 1 : <class 'numpy.str_'>
Data type of 3.14 : <class 'numpy.str_'>
Data type of True : <class 'numpy.str_'>
Data type of hello : <class 'numpy.str_'>


In [9]:
# 중첩 리스트 선언, 초기화
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [10]:
# 중첩 리스트 데이터 타입 확인
type(a)

list

In [11]:
# 중첩 리스트를 Numpy 배열로 변환 => 2차원 행렬로 변환
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
# 행렬 데이터 타입 확인
type(b)

numpy.ndarray

In [13]:
# Numpy 배열의 shape 확인
b.shape

(2, 3)

In [14]:
# Numpy 배열의 차원 확인
b.ndim

2

In [16]:
# Numpy 배열의 원소 개수 확인
b.size

6

In [17]:
# 2 x 3 행렬을 3 x 2 행렬로 변환
print(b.reshape(3,2 ))

[[1 2]
 [3 4]
 [5 6]]


In [18]:
# 배열 요소 데이터타입 변경: 정수 -> 실수
b = np.array(a, dtype=np.float64)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
# 배열 요소 데이터타입 변경: 실수 -> 정수
# 사후 변경 시 astype 메서드 활용하여 변경 가능
b = b.astype(np.int64)
print(b)

[[1 2 3]
 [4 5 6]]


## Numpy 배열 인덱싱

### 1차원 배열 인덱싱

In [23]:
# 새로운 배열 arr 생성
# 1차원 배열은 python의 리스트와 동일
arr = np.array([1, 2, 3, 4, 5])

In [24]:
print(arr)

[1 2 3 4 5]


In [25]:
print(arr[0])

1


In [26]:
print(arr[-1])

5


### 2차원 배열 인덱싱

In [28]:
# 2차원 배열 생성
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [31]:
# 1행 1열 원소 가져오기 -> arr[행, 열]로 명시하여 원하는 위치의 데이터에 접근 가능
arr_2d[1, 0]

4

### 배열 슬라이싱

In [33]:
arr_2d = np.arange(1, 7).reshape(2, 3) # arange(s, e) : s부터 e - 1까지의 수가 나열되어 저장
                                       # reshape(행, 열) : 배열의 모양을 재구성
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [36]:
# 두 번째 행 전체 출력
print(arr_2d[1, :])

# 세 번쨰 열 전체 출력
print(arr_2d[:, 2])

# 전체 행 두 번째 열부터 세 번째 열까지 출력, 아래 두 가지 표기 모두 사용 가능
print(arr_2d[:, (1, 2)])
print(arr_2d[:, 1:])

[4 5 6]
[3 6]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]


## Pandas 소개

### 데이터 생성

In [2]:
import pandas as pd

# 실습에 사용할 샘플 dictionary 생성
data = {
    '이름': ['아이유', '김연아', '홍길동', '강감찬', '장범준'],
    '학과': ['국문학', '수학',' 철학', '컴퓨터', '경영학'],
    '성적': [3.0, 1.0, 3.5, 2.7, 4.0]
}

# dictionary 타입을 pd.DataFrame() 인자로 넣어준다.
df = pd.DataFrame(data)
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동   철학  3.5
3  강감찬  컴퓨터  2.7
4  장범준  경영학  4.0

In [43]:
# 데이터프레임을 csv로 저장 -> to_csv 메소드 이용
# to_csv(저장경로/파일이름, sep=콤마로 구분, index=인덱스 번호 부여 x)
df.to_csv('./data/student.csv', sep=',', index=False)

In [3]:
# 데이터 로딩은 pandas의 read_csv를 활용하면 됨
df = pd.read_csv('./data/student.csv')
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동   철학  3.5
3  강감찬  컴퓨터  2.7
4  장범준  경영학  4.0

## Pandas 원하는 데이터 선택하기

### 1) 슬라이싱

In [46]:
# 데이터의 1번 행부터 4번 행까지 포함
display(df[1:5])

# 2번 행까지 포함
display(df[:3])

이름   학과   성적
1  김연아   수학  1.0
2  홍길동   철학  3.5
3  강감찬  컴퓨터  2.7
4  장범준  경영학  4.0

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동   철학  3.5

### 2) 인덱싱

#### Indexing

In [50]:
# Numpy처럼 df[1] 이렇게 인덱싱 할 수 없다.
# 1. 단순 인덱싱
df['이름']

0    아이유
1    김연아
2    홍길동
3    강감찬
4    장범준
Name: 이름, dtype: object

#### Fancy Indexing

In [57]:
# 인덱싱 시 리스트로 값을 주면 된다.
# df['이름','학과'] 와 같이 리스트가 아니라 그냥 문자열로 주게 되면 Syntax 에러가 발생한다.
# 열 속성의 순서를 바꾼다면, 그냥 바꾼대로 나온다.
display(df[['이름', '학과']])
display(df[['학과', '이름']])

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동   철학
3  강감찬  컴퓨터
4  장범준  경영학

학과   이름
0  국문학  아이유
1   수학  김연아
2   철학  홍길동
3  컴퓨터  강감찬
4  경영학  장범준

In [55]:
# 인덱싱 대상 열을 리스트로 주면 되기 때문에, 아래와 같이 사용할 수도 있다.
select_list = ['이름', '학과']
df[select_list]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동   철학
3  강감찬  컴퓨터
4  장범준  경영학

#### 슬라이싱 + 인덱싱

In [59]:
# 1~3행의 이름과 성적을 갖고 오기
select_list = ['이름', '성적']
df[1:4][select_list]

이름   성적
1  김연아  1.0
2  홍길동  3.5
3  강감찬  2.7

#### Boolean Indexing

In [61]:
df[df['학과'] == '수학']

이름  학과   성적
1  김연아  수학  1.0

### 3) loc & iloc 인덱서

In [5]:
# 한 개의 행에 대해서만 loc indexing
df.loc[3]

이름    강감찬
학과    컴퓨터
성적    2.7
Name: 3, dtype: object

In [4]:
# df.loc[3]에 대한 데이터 타입은?
type(df.loc[3])

pandas.core.series.Series

In [5]:
# 행에 대한 fancy indexing
df.loc[[1, 3, 4]]

이름   학과   성적
1  김연아   수학  1.0
3  강감찬  컴퓨터  2.7
4  장범준  경영학  4.0

In [12]:
# 행에 대해서 fancy 인덱싱과 column 슬라이싱
df.loc[[1, 3, 4], :'학과']

이름   학과
1  김연아   수학
3  강감찬  컴퓨터
4  장범준  경영학

In [13]:
# row fancy 인덱싱과 column fancy 인덱싱
df.loc[[1, 3, 4], ['이름', '성적']]

이름   성적
1  김연아  1.0
3  강감찬  2.7
4  장범준  4.0

In [15]:
# 그대로 iloc로 바꿔서 실습
df.iloc[[1, 3, 4], :2]

이름   학과
1  김연아   수학
3  강감찬  컴퓨터
4  장범준  경영학

In [17]:
df.iloc[[1, 3, 4], [0, 2]]

이름   성적
1  김연아  1.0
3  강감찬  2.7
4  장범준  4.0